FROM arm64v8/node:14

RUN apt-get update
# RUN apt-get install fonts-noto -y
# RUN apt-get install fonts-noto-color-emoji -y
# RUN fc-cache -fv
RUN apt-get install chromium-browser chromium-codecs-ffmpeg -y


# WORKDIR specifies the directory our
# application's code will live within
WORKDIR /app

# We copy our package.json file to our
# app directory
COPY package.json /app

# We then run npm install to install
# the npm dependencies for our application
RUN yarn install

# We then copy the rest of our application
# To the app directory
COPY src /app/src

# We start our application by calling
# npm start
CMD ["yarn", "start"]

EXPOSE 3000
